let domain = window.location.hostname;
let pagett = document.getElementById("page-title");
let tabtt = document.getElementById("tab-title");
let main_info = "404 - File or directory not found.";
let sub_info = "The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.";
let info0 = document.getElementById("info_0");
let info1 = document.getElementById("info_1");
pagett.innerHTML = domain + " - Client Error";
tabtt.innerHTML = main_info
info0.innerHTML = main_info;
info1.innerHTML = sub_info;